boot.o: boot.S multiboot.h x86_desc.h types.h
irq.o: irq.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h multiboot.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_init.o: idt_init.c lib.h types.h x86_desc.h idt_init.h irq.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  keyboard.h idt_init.h rtc.h filesys.h paging.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h lib.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c terminal.h types.h lib.h i8259.h keyboard.h
